config/routes.rb
Guia041::Application.routes.draw do

  concern :searchable do
    collection do
      get "autocomplete"
      get "search"
    end
  end

  resources :cities, concerns: :searchable
  resources :categories, concerns: :searchable
  resources :neighborhoods, concerns: :searchable
  resources :places, concerns: :searchable do
    collection do
      get "nearby"
    end

    resources :ratings, only: :update
  end

  root 'home#index'

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
	belongs_to :city
	has_many :places

	searchkick text_start: [:name], suggest: ['name'], autocomplete: ['name']
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  def autocomplete
    neighborhoods = Neighborhood.search(params[:w], autocomplete: true, :limit => 5).map(&:name).uniq
    respond_to do |format|
        format.json { render json: neighborhoods, status: :ok }
    end
  end

  def search
    neighborhoods = Neighborhood.search(params[:w], :limit => 5).map(&:name).uniq
    respond_to do |format|
        format.json { render json: neighborhoods, status: :ok }
    end
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to action: 'new' }
        #format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render action: 'show', status: :created, location: @neighborhood }
      else
        format.html { render action: 'new' }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:name, :city_id, :integer)
    end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_form.html.erb
<%= form_for(@neighborhood) do |f| %>
  <% if @neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% @neighborhood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.text_field :city_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/neighborhoods/edit.html.erb
<h1>Editing neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/index.html.erb
<h1>Listing neighborhoods</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= neighborhood.name %></td>
        <td><%= neighborhood.city_id %></td>
        <td><%= link_to 'Show', neighborhood %></td>
        <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood) %></td>
        <td><%= link_to 'Destroy', neighborhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighborhood', new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @neighborhood.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @neighborhood.city_id %>
</p>

<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>