config/routes.rb
Guia041::Application.routes.draw do

  concern :searchable do
    collection do
      get "autocomplete"
      get "search"
    end
  end

  resources :cities, concerns: :searchable
  resources :categories, concerns: :searchable
  resources :neighborhoods, concerns: :searchable
  resources :places, concerns: :searchable do
    collection do
      get "nearby"
    end

    resources :ratings, only: :update
  end

  root 'home#index'

end

app/models/place.rb
class Place < ActiveRecord::Base

  belongs_to :city
  belongs_to :neighborhood

  has_many :ratings

  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories, :allow_destroy => true

  searchkick language: "Portuguese", typeahead: [:title, :address], text_middle: [:title, :address], suggest: ['title', 'address'] , autocomplete: ['title', 'address']

  geocoded_by :full_address, :latitude => :lat, :longitude => :lon
  after_validation :geocode, :if => :address_changed?

  def search_data
    attributes.merge(categories: self.categories.map(&:title), rating: average_rating, neighborhood: Neighborhood.find(self.neighborhood_id).name )
  end

  def full_address
    "#{address}, #{number}, #{neighborhood.name} - #{city.name}"
  end

  def average_rating
    ratings.sum(:score) / ratings.size if ratings.size > 0
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index

    @places = Place.search("*", facets: [:neighborhood_id, :city_id, :categories], :limit => 30, :page => params[:page] )

    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.lat if place.lat.present?
      marker.lng place.lon if place.lon.present?
    end

  end

  def autocomplete
    if params[:address].present?
      places = Place.search(params[:address], partial: true, fields: [ {address: :text_middle, order: :asc } ], :limit => 5).map(&:address).uniq
    end

    if params[:place].present?
      places = Place.search( params[:place],  partial: true,  fields: [ {title: :text_middle, order: {_score: :desc}}] , :limit => 5).map(&:title).uniq
    end

    respond_to do |format|
        format.json { render json: places, status: :ok }
    end
  end


  def search

    where = ( Neighborhood.search(params[:w]).map(&:id) || Place.search( params[:w], suggest: true, fields: [ {address: :text_middle} ], order: {_score: :desc}, page: params[:page],  per_page: 30  ) ) if params[:w].present?

    if params[:w].present? && params[:q].present?
      localizacao = Neighborhood.search(params[:w]).map(&:id)
      if localizacao.any?
        @places = Place.search( params[:q], suggest: true, where: { neighborhood_id: localizacao }, facets: [:rating, :categories, :city_id], page: params[:page],  per_page: 30 )
      else
        address = Place.search( params[:w], suggest: true, fields: [ {address: :text_middle} ], order: {_score: :desc} ).map(&:address).first
        @places = Place.search( params[:q], suggest: true, fields: [:title], facets: [:neighborhood, :rating, :categories, :city_id], where: {address: address }, page: params[:page],  per_page: 30 )
      end
    elsif params[:w].present?
      localizacao = Neighborhood.search(params[:w]).map(&:id)
      if localizacao.any?
        @places = Place.search( "*", suggest: true, where: { neighborhood_id: localizacao },facets: [:neighborhood, :rating, :categories, :city_id], order: {_score: :desc}, page: params[:page],  per_page: 30 )
      else
        @places = Place.search( params[:w], suggest: true, fields: [ {address: :text_middle} ],facets: [:neighborhood, :rating, :categories, :city_id], order: {_score: :desc}, page: params[:page],  per_page: 30 )
      end
    elsif params[:q].present?
      @places = Place.search(params[:q], suggest: true, facets: [:neighborhood, :rating, :categories, :city_id], order: { rating: :desc }, page: params[:page],  per_page: 30)
    else
      #@places = Place.search("*")
      redirect_to places_path()
      return
    end

    marks = @places.select { |p| p if p.lat }

    @hash = Gmaps4rails.build_markers(marks) do |place, marker|
      marker.lat place.lat unless place.lat.nil?
      marker.lng place.lon unless place.lon.nil?
    end

    render 'search'
  end


  def nearby

    search = Place.search do
       keywords( params[:q] ) if params[:q].present?
       with(:location).near([ params[:lat], params[:lon] ], 5 ) if (params[:lat].present?) && (params[:lon].present?)
       order_by(:score, :asc)
       #with(:geohash).near( -25.480876, -49.304425, :precision => 1)
    end

    @places = search.results # Adiciona um lugar para traçar o trajeto # Adiciona um lugar para traçar o trajeto

    @distances = search

    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.lat if place.lat.present?
      marker.lng place.lon if place.lon.present?
    end

    render 'index'
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @place.categories.build
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :description, :address, :neighborhood_id, :number, :cep, :city_id, :state, :phone, category_ids: [])
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_category_fields.html.erb
<div class="form-group">
	<div class="row">
		<div class="col-sm-6">
			<%= f.label :Category %>
			<%= f.select :title, Category.all.map(&:title), {}, :class=>"form-control"%>
	<%#= f.text_field :value, :class=>"form-control input-email" %>
    		<%= f.hidden_field :_destroy %>
    <%#= link_to content_tag(:i, "", class:"glyphicon glyphicon-trash"), '#', class: "remove_fields btn btn-danger" %>
    	</div>
    </div>
</div>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
<% if @place.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

  <ul>
    <% @place.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class => 'form-control'  %>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-sm-3 col-offset-3">
      <%= f.label :cep %>
      <%= f.text_field :cep, :class => 'form-control'  %>
    </div>
    <div class="col-sm-3 col-offset-3">
      <%= f.label :phone %>
      <%= f.text_field :phone, :class => 'form-control'  %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-sm-9">
      <%= f.label :address %>
      <%= f.text_field :address, :class => 'form-control'  %>
    </div>
    <div class="col-sm-3">
      <%= f.label :number %>
      <%= f.text_field :number, :class => 'form-control'  %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-sm-4">
      <%= f.label :neighborhood %>
      <%= f.select :neighborhood_id, Neighborhood.order(:name).map { |neighborhood| [neighborhood.name, neighborhood.id] }, {}, {:class => 'form-control'}  %>
    </div>
    <div class="col-sm-4">
      <%= f.label :city %>
     <%= f.select :city_id, City.order(:name).map { |city| [city.name, city.id] }, {}, {:class => 'form-control'}  %>
    </div>
    <div class="col-sm-4">
      <%= f.label :state %>
      <%= f.text_field :state, :class => 'form-control'  %>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.label :category_ids, "Categories" %>
  <%= f.collection_select :category_ids, Category.order(:title), :id, :title, {:selected => @place.category_ids,  :include_blank => false}, {:class=> 'form-control', multiple: true} %>
</div>
<%#= link_to_add_fields content_tag(:i, "", class:"glyphicon glyphicon-plus") + " " + t('button.contact.add'), f, :categories, "btn btn-xs btn-success pull-right" %>

<%#= f.fields_for :categories do |builder| %>
  <%#= render 'category_fields', f: builder %>
<%# end %>

<div class="actions">
  <%= f.submit :class => 'btn btn-success' %>
</div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div style="width: 70%;float: left">
  <div class="table-responsive">
    <table class="table table-condensed" style="font-size: 10px">
      <thead>
        <tr>
          <th>TITULO</th>
          <th>ENDEREÇO</th>
          <th>SCORE</th>
      <!--th>Lon</th>
      <th>Score</th>
      <th></th>
      <th></th>
      <th></th-->
      </tr>
    </thead>
    <tbody>
      <% @places.each do |place| -%>
      <tr>
        <td><%= place.title %></td>
        <td><%= place.full_address %></td>
        <td><%#= hit["_score"] %></td>
        <td><%= link_to 'Show', place %> - <%= link_to 'Edit', edit_place_path(place) %> - <%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      <!--td><%= link_to 'Show', place %></td>
      <td><%= link_to 'Edit', edit_place_path(place) %></td>
      <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
      <% end %>


    </tbody>
  </table>
  <%#= paginate @places %>
</div>

<%= link_to 'New Place', new_place_path, :class=> "btn btn-success" %>
</div>
<div style='width: 300px; float: right'>
  <div id="map" style='width: 300px; height: 300px;'></div>
  <hr>
</div>


<%= content_for(:js) do %>
<script src="http://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='http://google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<script type="text/javascript">
var handler = Gmaps.build('Google');

handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>
<% end %>

app/views/places/new.html.erb
<div class="container">
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>
</div>

app/views/places/search.html.erb
<div id="conteudo">
  <div id="mapOverlay">
    <div id="map"></div>
  </div>

  <div id="results">
    <div class="filtros">
      <ul>
      <li><h3><strong><%= @places.total_count %></strong> resultados encontrados com <strong class="text-danger"><%=params[:q]%></strong><h3></li>
        <li><h5><%= page_entries_info @places %><h5></li>

        <% unless @places.suggestions.empty? %>
          <li>Você quis dizer <a href="?q=<%= @places.suggestions.first %>"><%= @places.suggestions.first %></a></li>
        <% end %>
      </ul>
    </div>
    <div class="resultados">
      <ul>
        <% @places.each_with_index do |place, i| %>
        <li>
          <%= link_to place.title, place_path(place) %>
          <% if place.average_rating %>
          <span class="rating" data-score="<%= place.average_rating %>"></span>
          <% end %>
          <p><%=place.full_address()%></p>
          <p class="phone"><%=place.phone%></p>
          <hr>
        </li>
        <% end %>
      </ul>

      <%= paginate @places %>
    </div>
  </div>
</div>

<!--div style="width: 70%;float: left">

  <hgroup class="mb20">
    <h1>Search Results</h1>
    <h2 class="lead"><%=pluralize(@places.count, "place")%> results were found for the search for <strong class="text-danger"><%=params[:q]%></strong> <% if params[:w] %> perto <strong class="text-danger"><%=params[:w]%></strong> <% end %></h2>
  </hgroup>
  <section class="col-xs-10 col-sm-6 col-md-10">

    <% @places.each_with_hit do |place, hit| %>
    <article class="search-result row">
      <div class="info">
        <div class="col-sm-2">
          <a href="#" title="<%=place.title%>"><img src="http://lorempixel.com/120/90/food?rand=<%=place.id%>" alt="Lorem ipsum" /></a>
        </div>
        <div class="col-sm-8">
          <h3 class="title"><%= link_to place.title, place_path(place) %></h3>
          <span class="rating" data-score="<%= place.average_rating %>"></span>
          <p><%=place.full_address()%></p>
          <p class="phone"><%=place.phone%></p>
        </div>
        <div class="col-sm-2">
          <button class="btn btn-xs btn-success">Get Directions</button>
          <button class="btn btn-xs btn-danger">More info</button>
          <button class="btn btn-xs btn-alert">Visit website</button>
        </div>
      </div>
    </article>
    <% end %>
  </section>
  <section class="col-xs-2 col-sm-6 col-md-2">
    <% @places.facets.each do |filter| %>
    <ul><span><%=filter.first%></span>
      <% @places.facets[filter.first]['terms'].each do |term| %>
      <li style="font-size: 10px;"><%= term['term'] %> (<%= term['count']%>)</li>
      <% end %>
    </ul>
    <% end %>
  </section>
  <%= paginate @places %>
</div>

<div style='width: 300px; float: right'>
  <div id="map" style='width: 300px; height: 300px;'></div>
</div-->

<%= content_for(:js) do %>
<script src="http://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='http://google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<script type="text/javascript">
  var handler = Gmaps.build('Google');

  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>
<% end %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<p>Titulo: <%= @place.title %></p>
<p>Desc<%= @place.description %></p>
<p>CEP: <%= @place.cep %></p>
<p>ENDEREÇO: <%= @place.full_address %></p>
<p>ESTADO: <%= @place.state %></p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>